// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolManagement.Infrastructure.Data;

#nullable disable

namespace SchoolManagement.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260402174907_SeedMockData")]
    partial class SeedMockData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.Property<string>("TeacherEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeacherFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeacherLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassCode = "10A-2026",
                            ClassName = "Class 10A",
                            SchoolId = 1,
                            TeacherEmail = "ramesh@test.com",
                            TeacherFirstName = "Ramesh",
                            TeacherLastName = "Kumar"
                        },
                        new
                        {
                            Id = 2,
                            ClassCode = "10B-2026",
                            ClassName = "Class 10B",
                            SchoolId = 1,
                            TeacherEmail = "saritha@test.com",
                            TeacherFirstName = "Saritha",
                            TeacherLastName = "Nair"
                        },
                        new
                        {
                            Id = 3,
                            ClassCode = "9A-2026",
                            ClassName = "Class 9A",
                            SchoolId = 2,
                            TeacherEmail = "manoj@test.com",
                            TeacherFirstName = "Manoj",
                            TeacherLastName = "Pillai"
                        });
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Schools");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Trivandrum",
                            City = "TVM",
                            Postcode = "695001",
                            SchoolName = "Kerala Model School",
                            State = "Kerala"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Kochi",
                            City = "EKM",
                            Postcode = "682001",
                            SchoolName = "St. Marys High School",
                            State = "Kerala"
                        });
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassId = 1,
                            DateOfBirth = new DateTime(2010, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rahul@test.com",
                            FirstName = "Rahul",
                            Gender = "Male",
                            IsActive = true,
                            LastName = "Nair",
                            Points = 10
                        },
                        new
                        {
                            Id = 2,
                            ClassId = 1,
                            DateOfBirth = new DateTime(2010, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sneha@test.com",
                            FirstName = "Sneha",
                            Gender = "Female",
                            IsActive = true,
                            LastName = "V",
                            Points = 15
                        },
                        new
                        {
                            Id = 3,
                            ClassId = 2,
                            DateOfBirth = new DateTime(2010, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "arjun@test.com",
                            FirstName = "Arjun",
                            Gender = "Male",
                            IsActive = true,
                            LastName = "K",
                            Points = 5
                        },
                        new
                        {
                            Id = 4,
                            ClassId = 3,
                            DateOfBirth = new DateTime(2011, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "meera@test.com",
                            FirstName = "Meera",
                            Gender = "Female",
                            IsActive = true,
                            LastName = "S",
                            Points = 20
                        });
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "teacher@test.com",
                            IsActive = true,
                            PasswordHash = "/3vZexp3id3Sd1Ei/WgX8xc2ctqfgCzuxX8oQyW/WJ8=",
                            Role = "Teacher"
                        });
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Class", b =>
                {
                    b.HasOne("SchoolManagement.Domain.Entities.School", "School")
                        .WithMany("Classes")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Student", b =>
                {
                    b.HasOne("SchoolManagement.Domain.Entities.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Class", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.School", b =>
                {
                    b.Navigation("Classes");
                });
#pragma warning restore 612, 618
        }
    }
}
